### ISSUE TITLE
Game glitches out when loading save files more than once?

### ISSUE THREAD

**Issue by myry43** [Dialogic-Godot/visual-novel-template#2]
I'm sorry if I'm not able to explain this very well, coding isn't my strongest suite.

The demo works otherwise very well, and I love how easy it is to use! However, there's been some issues I've run to. When running the demo, it was giving me errors about not being able to save into "user://dialogic/"+slot_name+"/thumbnail.png", which partially went away when I changed that to "res://" instead of "user://". But I also needed to add
```
var directory = Directory.new()
directory.make_dir("res://dialogic/" + slot_name)
```
to the **DialogicMenus_SaveMenu.gd**-script, because there didn't seem to be code where it actually creates the folder for the save slots. This got rid of the errors, and I thought that was that.

The saved thumbnails actually show in the save folders, but they're not showing in the game (just a black screen with numbers). Couldn't find a point in the code where it actually sets the thumbnail into the slot view? And the biggest issue is, that when you press Load button multiple times (not in a row, but like loading the save files multiple times during the runtime), the window just freezes, where it still shows the dialogue box (and the characters/background depending what part you are in the game) and the menu music plays on the background. If there's transitions, like character moving on screen, it will freeze midway through that.
This problem is fixed by just pressing one of the two other buttons (Save or Settings) which will pop up the menu screen up normally. I tried to look through code but couldn't figure out why it works like this.

This doesn't render the game unplayable, but is obviously pretty clear nuisance if you're playing the game and loading a file more than once during runtime. I know this is just a showcase template but besides this problem, it works perfectly for me, and I could make a whole VN with this!

**Comment by Jowan-Spooner** [comment]
Thanks for letting us know. I can't reproduce the error with the thumbnail. Did you make any changes to the Menu scenes / scripts? It works fine for me... 

I was able to reproduce the second thing with the game freezing when loading. I will look into it and push a fix asap.

**Comment by Jowan-Spooner** [comment]
I think I found the cause for the second problem with the crash after loading a save. I've pushed a fix to main. If you've already made big changes and don't want to reset your progress I can write you how to fix it on discord.

**Comment by myry43** [comment]
I think the thumbnail error might've come in the process of not importing the project and scanning it instead, and then trying to run it without the Dialogic plugin enabled at first? Just a guess, I didn't do any changes before testing it out a few times. But I downloaded it again now, and I don't have either of the problems anymore. Thank you!

**Comment by Jowan-Spooner** [comment]
Great to hear that. If you have other suggestions or problems, feel free to let me know here!
