### ISSUE TITLE
Game allows for only two save slots, overwrites Save 1 if trying to create more

### ISSUE THREAD

**Issue by myry43** [Dialogic-Godot/visual-novel-template#3]
Hello again! I noticed that when trying to save more than a couple of times, it wouldn't create more save slots, but instead just saves over the Slot 1. At one point I was able to create three save slots by deleting Save 0, and saving again. Trying to save after that resulted in Save 3 being overwritten. I downloaded a fresh version of this and didn't do any changes besides adding more Text Events to have some more lenght of the game to test on. I detected that by adding more save folders in user://dialogic/, they would show normally in the Save/Load screens, so I guess the error happens whilst it's trying to create more than a couple of save slots?

I also noticed that right-clicking the save files won't actually delete them, even though there's a text box under them saying you can do that? I don't really see this as much of an issue because you can still delete them by pressing the little x's, but just letting you know.
And another thing I was wondering is that when you click Save/Load/Settings -buttons on the game view, it advances text at the same time. I'm not sure if this is on purpose. What I did back in Unity, when trying to make a VN, was to have little trigger boxes around the buttons, so that when your mouse is inside them, it wouldn't trigger the dialogue to advance. Maybe something similar is possible in Godot as well?

**Comment by Jowan-Spooner** [comment]
I've fixed the save file overwriting and removed the old label. 

The thing with the buttons at the bottom is a bit harder (because dialogic uses a input action), but I'll see what I can do.
