### ISSUE TITLE
Are you planning to create a template with dialogic2?

### ISSUE THREAD

**Issue by PoliyasRoden** [Dialogic-Godot/visual-novel-template#4]
The language may not be correct due to the use of translations, please forgive us. 

Recently dialogic2 came out for godot4.0, do you think you could provide a template for it?

There are many new features in dialogic2 and I would like to work with it.

I hope you have a plan.
Thanks for the good template.

**Comment by CakeVR** [comment]
Hello, we have a guide on how to use Dialogic 2: https://dialogic-docs.coppolaemilio.com/introduction.html

The `visual-novel-template` repository is outdated. It has not been updated for a long time.
I recommend to use the Visual Novel style part of Dialogic 2.

If you have any further questions, let me know.

**Comment by coppolaemilio** [comment]
> Recently dialogic2 came out for godot4.0, do you think you could provide a template for it?

There will be a template for Dialogic 2 when we are out of alpha. That way, we don't have to remake it every time we make breaking changes to it. So yes, it will be done, but it will have to wait a little longer.

Closing the issue for now, but feel free to reopen if needed.
